name: "? Question"
description: General questions about the container
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Please do not use this form for technical issues, and make sure to check the [FAQ](https://github.com/dockur/windows/blob/master/readme.md) first!
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What's the question you have about the container?
    validations:
      required: true
