services:
  windows:
    container_name: windows
    image: ghcr.io/dockur/windows
    environment:
      RAM_SIZE: "half"
      DISK_SIZE: "256G"
      CPU_CORES: "max"
      USERNAME: "Heather"
      PASSWORD: "heather"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: on-failure
    stop_grace_period: 2m
