services:
  windows:
    container_name: windows
    image: ghcr.io/dockur/windows
     environment:
      VERSION: "2025"
    DISK_SIZE: "509G"
       MANUAL: "Y"
   DISK2_SIZE: "639G"
   DISK3_SIZE: "643G"
     devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
      - ./disk2:/storage2
      - ./disk3:/storage3
   restart: always
    stop_grace_period: 2m
