name: XP PC Validation

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: xp-pc-validation-${{ github.ref }}
  cancel-in-progress: true

jobs:
  xp:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: host + no OSVW
            cpu: host
            cpu_flags: osvw=off

          - name: host + no AMD legacy features
            cpu: host
            cpu_flags: osvw=off,topoext=off,cr8legacy=off,svm=off,x2apic=off

          - name: qemu32
            cpu: qemu32
            cpu_flags: ""

          - name: kvm32
            cpu: kvm32
            cpu_flags: ""

          - name: Opteron G1
            cpu: Opteron_G1
            cpu_flags: ""

          - name: Opteron G2
            cpu: Opteron_G2
            cpu_flags: ""

          - name: Opteron G3
            cpu: Opteron_G3
            cpu_flags: ""

          - name: host
            cpu: host
            cpu_flags: ""

    name: Windows XP x86 - pc - ${{ matrix.name }}

    uses: ./.github/workflows/install.yml
    with:
      name: XP pc + ${{ matrix.name }} + blk
      version: "xp"
      callback: legacy
      machine: pc
      cpu: ${{ matrix.cpu }}
      cpu_flags: ${{ matrix.cpu_flags }}
      disk_type: blk
      kill_on_failure: true
      expected_caption: Windows XP
      minimum_build: 2600
      platform: x86
