name: Validation

on:
  release:
    types:
      - published

  workflow_dispatch:

  push:
    branches:
      - test
    paths:
      - ".github/workflows/install.yml"
      - ".github/workflows/validate.yml"

permissions:
  contents: read

concurrency:
  group: validation-${{ github.ref }}
  cancel-in-progress: true

jobs:
  desktop:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows 11 Pro
            version: "11"
            expected_caption: Windows 11
            expected_edition: Professional
            minimum_build: 22000
            platform: x64

          - name: Windows 11 LTSC
            version: "11l"
            expected_caption: Windows 11
            expected_edition: EnterpriseS
            minimum_build: 26100
            platform: x64

          - name: Windows 11 Enterprise
            version: "11e"
            expected_caption: Windows 11
            expected_edition: Enterprise
            minimum_build: 22000
            platform: x64

          - name: Windows 11 IoT Enterprise
            version: "11i"
            expected_caption: Windows 11
            expected_edition: IoTEnterpriseS
            minimum_build: 26100
            platform: x64

          - name: Windows 10 Pro
            version: "10"
            expected_caption: Windows 10
            expected_edition: Professional
            minimum_build: 10240
            platform: x64

          - name: Windows 10 LTSC
            version: "10l"
            expected_caption: Windows 10
            expected_edition: EnterpriseS
            minimum_build: 17763
            platform: x64

          - name: Windows 10 Enterprise
            version: "10e"
            expected_caption: Windows 10
            expected_edition: Enterprise
            minimum_build: 10240
            platform: x64

          - name: Windows 10 IoT Enterprise
            version: "10i"
            expected_caption: Windows 10
            expected_edition: IoTEnterpriseS
            minimum_build: 19044
            platform: x64

          - name: Windows 8.1 Enterprise
            version: "8e"
            expected_caption: Windows 8.1
            expected_edition: Enterprise
            minimum_build: 9600
            platform: x64

    name: ${{ matrix.name }}
    uses: ./.github/workflows/install.yml
    with:
      name: ${{ matrix.name }}
      version: ${{ matrix.version }}
      expected_caption: ${{ matrix.expected_caption }}
      expected_edition: ${{ matrix.expected_edition }}
      minimum_build: ${{ matrix.minimum_build }}
      platform: ${{ matrix.platform }}

  tiny:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Nano11
            version: "nano11"
            expected_caption: Windows 11
            minimum_build: 22000
            platform: x64

          - name: Core11
            version: "core11"
            expected_caption: Windows 11
            minimum_build: 22000
            platform: x64

          - name: Tiny11
            version: "tiny11"
            expected_caption: Windows 11
            minimum_build: 22000
            platform: x64

          - name: Tiny10
            version: "tiny10"
            expected_caption: Windows 10
            minimum_build: 19041
            platform: x64

    name: ${{ matrix.name }}
    uses: ./.github/workflows/install.yml
    with:
      name: ${{ matrix.name }}
      version: ${{ matrix.version }}
      expected_caption: ${{ matrix.expected_caption }}
      minimum_build: ${{ matrix.minimum_build }}
      platform: ${{ matrix.platform }}

  server:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows Server 2025
            version: "2025"
            expected_caption: Windows Server 2025
            minimum_build: 26100
            platform: x64

          - name: Windows Server 2022
            version: "2022"
            expected_caption: Windows Server 2022
            minimum_build: 20348
            platform: x64

          - name: Windows Server 2019
            version: "2019"
            expected_caption: Windows Server 2019
            minimum_build: 17763
            platform: x64

          - name: Windows Server 2016
            version: "2016"
            expected_caption: Windows Server 2016
            minimum_build: 14393
            platform: x64

          - name: Windows Server 2012 R2
            version: "2012"
            expected_caption: Windows Server 2012 R2
            minimum_build: 9600
            platform: x64

    name: ${{ matrix.name }}
    uses: ./.github/workflows/install.yml
    with:
      name: ${{ matrix.name }}
      version: ${{ matrix.version }}
      expected_caption: ${{ matrix.expected_caption }}
      minimum_build: ${{ matrix.minimum_build }}
      platform: ${{ matrix.platform }}

  legacy:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows 7 Ultimate
            version: "7u"
            cpu: host
            expected_caption: Windows 7
            minimum_build: 7601
            platform: x64

          - name: Windows 7 Ultimate x86
            version: "7x86"
            cpu: host
            expected_caption: Windows 7
            minimum_build: 7601
            platform: x86

          - name: Windows Vista Ultimate
            version: "vu"
            cpu: host
            expected_caption: Windows Vista
            minimum_build: 6002
            platform: x64

          - name: Windows Vista Ultimate x86
            version: "vistax86"
            cpu: host
            expected_caption: Windows Vista
            minimum_build: 6002
            platform: x86

          - name: Windows XP Professional
            version: "xp"
            cpu: qemu32 # Remove after 6.03
            expected_caption: Windows XP
            minimum_build: 2600
            platform: x86

          - name: Windows XP Professional x64
            version: "xp64"
            cpu: host
            expected_caption: Windows XP
            minimum_build: 3790
            platform: x64

          - name: Windows 2000 Professional
            version: "2k"
            cpu: host
            expected_caption: Windows 2000
            minimum_build: 2195
            platform: x86

          - name: Windows Server 2008 R2
            version: "2008"
            cpu: host
            expected_caption: Windows Server 2008 R2
            minimum_build: 7601
            platform: x64

          - name: Windows Server 2003 R2
            version: "2003"
            cpu: host
            expected_caption: Windows Server 2003
            minimum_build: 3790
            platform: x64

    name: ${{ matrix.name }}
    uses: ./.github/workflows/install.yml
    with:
      name: ${{ matrix.name }}
      version: ${{ matrix.version }}
      callback: legacy
      cpu: ${{ matrix.cpu }}
      expected_caption: ${{ matrix.expected_caption }}
      minimum_build: ${{ matrix.minimum_build }}
      platform: ${{ matrix.platform }}

  arm:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows 11 Pro ARM64
            version: "11"
            expected_caption: Windows 11
            expected_edition: Professional
            minimum_build: 22000
            platform: arm64

          - name: Windows 11 Enterprise ARM64
            version: "11e"
            expected_caption: Windows 11
            expected_edition: Enterprise
            minimum_build: 22000
            platform: arm64

          - name: Windows 11 LTSC ARM64
            version: "11l"
            expected_caption: Windows 11
            expected_edition: EnterpriseS
            minimum_build: 26100
            platform: arm64

          - name: Windows 11 IoT Enterprise ARM64
            version: "11i"
            expected_caption: Windows 11
            expected_edition: IoTEnterpriseS
            minimum_build: 26100
            platform: arm64

          - name: Windows 10 Pro ARM64
            version: "10"
            expected_caption: Windows 10
            expected_edition: Professional
            minimum_build: 10240
            platform: arm64

          - name: Windows 10 Enterprise ARM64
            version: "10e"
            expected_caption: Windows 10
            expected_edition: Enterprise
            minimum_build: 10240
            platform: arm64

          - name: Windows 10 LTSC ARM64
            version: "10l"
            expected_caption: Windows 10
            expected_edition: EnterpriseS
            minimum_build: 17763
            platform: arm64

          - name: Windows 10 IoT Enterprise ARM64
            version: "10i"
            expected_caption: Windows 10
            expected_edition: IoTEnterpriseS
            minimum_build: 19044
            platform: arm64

          - name: Tiny11 ARM64
            version: "tiny11"
            expected_caption: Windows 11
            expected_edition: ""
            minimum_build: 22000
            platform: arm64

          - name: Core11 ARM64
            version: "core11"
            expected_caption: Windows 11
            expected_edition: ""
            minimum_build: 22000
            platform: arm64

    name: ${{ matrix.name }}
    uses: ./.github/workflows/install.yml
    with:
      name: ${{ matrix.name }}
      version: ${{ matrix.version }}
      runner: ubuntu-24.04-arm
      expected_caption: ${{ matrix.expected_caption }}
      expected_edition: ${{ matrix.expected_edition }}
      minimum_build: ${{ matrix.minimum_build }}
      platform: ${{ matrix.platform }}
