name: x86 NX Validation

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: x86-nx-validation-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows 7 x86 - NX
            version: "7x86"
            expected_caption: Windows 7
            minimum_build: 7601

          - name: Windows Vista x86 - NX
            version: "vistax86"
            expected_caption: Windows Vista
            minimum_build: 6002

          - name: Windows XP x86 - NX test 1
            version: "xp"
            expected_caption: Windows XP
            minimum_build: 2600

          - name: Windows XP x86 - NX test 2
            version: "xp"
            expected_caption: Windows XP
            minimum_build: 2600

    name: ${{ matrix.name }}

    uses: ./.github/workflows/install.yml
    with:
      name: ${{ matrix.name }}
      version: ${{ matrix.version }}
      branch: dev
      callback: legacy
      cpu_flags: nx=off
      kill_on_failure: false
      expected_caption: ${{ matrix.expected_caption }}
      minimum_build: ${{ matrix.minimum_build }}
      platform: x86
